// Backwards-compatibility shim — canonical implementation is in @kombuse/core/logger
export {
  createSessionLogger,
  createAppLogger,
  setAppLoggerOnLog,
  pruneOldLogs,
  closeAppLogger,
  setLogDir,
  setLogTarget,
  getConfiguredLogDir,
  resetLogConfig,
  type SessionLogger,
  type SessionLoggerOptions,
  type AppLogger,
  type AppLoggerOptions,
  type AppLogCallback,
  type LogTarget,
  type LogLevel,
  type AppLogLevel,
  type PruneOptions,
} from '@kombuse/core/logger'
